#setwd("E:\\Coursera\\Exploratory Data Analysis\\Course Project 1")
par(mfrow=c(2,2))
epc<-read.csv2("household_power_consumption.txt", colClasses="character")
z=(epc[,1] == "2/2/2007" | epc[,1] == "1/2/2007")
epc<-subset(epc,z)

datetime <- strptime( paste(epc$Date,epc$Time), format="%d/%m/%Y %H:%M:%S")

with(epc, plot(datetime, Global_active_power, type="l",xlab="",ylab="Global Active Power"))
with(epc, plot(datetime, Voltage, type="l"))
plot (datetime,epc$Sub_metering_1,type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines (datetime,epc$Sub_metering_2,type = "l", col = "red")
points (datetime,epc$Sub_metering_3,type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
with(epc, plot(datetime, Global_reactive_power, type="l"))

png("Plot4.png")
par(mfrow=c(2,2))
with(epc, plot(datetime, Global_active_power, type="l",xlab="",ylab="Global Active Power"))
with(epc, plot(datetime, Voltage, type="l"))
plot (datetime,epc$Sub_metering_1,type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines (datetime,epc$Sub_metering_2,type = "l", col = "red")
points (datetime,epc$Sub_metering_3,type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
with(epc, plot(datetime, Global_reactive_power, type="l"))
dev.off()