#setwd("E:\\Coursera\\Exploratory Data Analysis\\Course Project 1")
epc<-read.csv2("household_power_consumption.txt", colClasses="character")
z=(epc[,1] == "2/2/2007" | epc[,1] == "1/2/2007")
epc<-subset(epc,z)
epc[,3]<-as.numeric(epc[,3])
hist(epc$Global_active_power,xlab="Global Active Power (kilowatts)",main = "Global Active Power",col="red")
png("Plot1.png")
hist(epc$Global_active_power,xlab="Global Active Power (kilowatts)",main = "Global Active Power",col="red")
dev.off()