
#setwd("E:\\Coursera\\Exploratory Data Analysis\\Course Project 1")
epc<-read.csv2("household_power_consumption.txt", colClasses="character")
z=(epc[,1] == "2/2/2007" | epc[,1] == "1/2/2007")
epc<-subset(epc,z)
epc[,7]<-as.numeric(epc[,7])
epc[,8]<-as.numeric(epc[,8])
epc[,9]<-as.numeric(epc[,9])
datetime <- strptime( paste(epc$Date,epc$Time), format="%d/%m/%Y %H:%M:%S")

plot (datetime,epc$Sub_metering_1,type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines (datetime,epc$Sub_metering_2,type = "l", col = "red")
points (datetime,epc$Sub_metering_3,type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))

png("Plot3.png")
plot (datetime,epc$Sub_metering_1,type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines (datetime,epc$Sub_metering_2,type = "l", col = "red")
points (datetime,epc$Sub_metering_3,type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
dev.off()